### ISSUE TITLE
Unnecessary duplication of templates?

### ISSUE THREAD

**Issue by sebbASF** [apache/template-site#4]
It looks like the intention is for every site to have copies of the templates.

Whilst that might perhaps be sensible for the data template, as presumably that will need to vary between sites, it seems very strange to require every site to have a copy of the asfgenid and asfreader plugins.

AFAICT that will make for a long-term maintenance headache.

Plugins that can be shared between all sites should be centrally deployed.

Ideally the data template should be shared, and a configuration file used to determine what data is to be extracted. If a site has a unique data requirement, then they can provide their own code, but otherwise the code should be centralised. Sites that find they need additional data items should be encouraged to contribute the code back to the central data extraction plugin.

**Comment by dave2wave** [comment]
Plugins are all moving to the infrastructure-pelican repository.

templates has tests of plugins and more may be added
